#version 460
#extension GL_EXT_ray_tracing : require

layout(binding = 3, rgba8) uniform image2D storageImage;
layout(set = 0, binding = 4) uniform accelerationStructureEXT topLevelAS;
layout(location = 0) rayPayloadEXT vec3 hitColor;

void main() {
    vec3 origin = vec3(0.0, 0.0, -5.0);
    vec3 direction = normalize(vec3(gl_LaunchIDEXT.xy - vec2(0.5), 1.0));
    ivec2 pixelCoords = ivec2(gl_LaunchIDEXT.xy);
    ivec2 imageSize = imageSize(storageImage);
    vec2 coords = vec2(pixelCoords) / vec2(imageSize);
    hitColor = vec3(0.0); // Default color in case the ray misses
    vec4 outputColor = vec4(coords.x,
                            coords.y,
                            1-coords.x,
                            1.0);


    traceRayEXT(
        topLevelAS, 
        gl_RayFlagsOpaqueEXT, 
        0xFF, 
        0,    // SBT record offset
        1,    // SBT record stride
        0,    // Miss shader index
        origin, 
        0.0, 
        direction, 
        100.0, 
        0 // location of the payload
    );


    // Write the color to the storage image
    imageStore(storageImage, pixelCoords, outputColor);
}

