#version 460
#extension GL_EXT_ray_tracing : require
#include "include/types.h"
#include "include/random.h"

layout(binding = 3, rgba8) uniform image2D storageImage;
layout(set = 0, binding = 4) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 5) uniform CameraBlock {
    vec4 position;  // Camera position
    vec4 forward; // Camera direction (where it's looking)
    vec4 right; // Camera direction (where it's looking)
    vec4 up;        // Up vector
    float fov;          // Field of view
    float yaw;
    float pitch;
    bool reset;
} camera;
layout(set = 0, binding = 6, std430)buffer WaveFrontBuffer {
    RayState waveFront[];
};
layout(location = 0) rayPayloadEXT RayPayload rayPayload;

int get1DIndex(int x, int y, int width) {
    return y * width + x;
}

void main() {

    ivec2 pixelCoords = ivec2(gl_LaunchIDEXT.xy);
    ivec2 imageSize = imageSize(storageImage);
    int idx = get1DIndex(pixelCoords.x, pixelCoords.y, imageSize.y);
    if (waveFront[idx].randomState == 0){
        waveFront[idx].randomState = hashCoords(pixelCoords.x, pixelCoords.y);
    }
    
    float xi1 = 2*fastRandom(waveFront[idx].randomState)-1;
    float xi2 = 2*fastRandom(waveFront[idx].randomState)-1;
    vec2 coords = vec2(pixelCoords+vec2(xi1,xi2)) / vec2(imageSize);
    vec2 ndc = 2*(coords) - vec2(1.0);
    ndc.y = -ndc.y;


    vec3 origin=waveFront[idx].origin.xyz;
    vec3 direction=waveFront[idx].direction.xyz;
    if(camera.reset || waveFront[idx].terminated) {
        waveFront[idx].light = vec4(0);
        waveFront[idx].throughPut = vec4(1.0);
        waveFront[idx].terminated = false;
        origin = camera.position.xyz; 
        direction = ndc.x*camera.right.xyz + ndc.y*camera.up.xyz + camera.fov*camera.forward.xyz; // Ray direction pointing forward
        direction = normalize(direction); 
    }
    if(camera.reset) {
        waveFront[idx].samples = 0;
    }
    
    rayPayload.idx = idx;
    traceRayEXT(
        topLevelAS, 
        gl_RayFlagsOpaqueEXT, 
        0xFF, 
        0,    // SBT record offset
        1,    // SBT record stride
        0,    // Miss shader index
        origin, 
        0.0, 
        direction, 
        100.0, 
        0 // location of the payload
    );

    if(fastRandom(waveFront[idx].randomState) < 0.1) {
        waveFront[idx].terminated = true;
    }

    if(camera.reset){
        float miss = min(rayPayload.hitDistance, 1.0f);
        imageStore(storageImage, pixelCoords, waveFront[idx].throughPut * miss);
    }
    
    if(waveFront[idx].terminated) {
        vec4 currentPixel = imageLoad(storageImage, pixelCoords);
        vec4 newPixel = (currentPixel *  waveFront[idx].samples + waveFront[idx].light) / ( waveFront[idx].samples + 1);
        imageStore(storageImage, pixelCoords, newPixel);
        waveFront[idx].samples += 1;
    }

    // Write the color to the storage image
}

